[package]
name = "bft-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bft-types = { path = "../bft-types" }
serde = { workspace = true }
bincode = { workspace = true }
crc32fast = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
